version: '3'
services:
  # PostgreSQL database
  payment_service_db:
    image: postgres:latest
    container_name: payment_service_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"    
    volumes:
      - ./postgres_data:/var/lib/postgresql/data