version: '3'
services:  
  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: postgres_webinterface
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "6420:80"